# Generated by Django 5.1.2 on 2024-10-13 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='upload_at',
            new_name='updated_at',
        ),
    ]
